version: '3.5'
services:
  postgres:
    container_name: postgres-article
    image: postgres:latest
    environment:
      POSTGRES_DB: controle_de_feira
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"